#!/bin/bash
SESSION=`basename $PWD`

tmux -2 new-session -d -s 'code'

# window-1
tmux rename-window -t 'code':1 'vim'
tmux split-window   -v -p 30

# window-2
tmux new-window -t 'code' -a -n 'git'
tmux split-window -v -p 30

# window-3
tmux new-window -t 'code' -a -n 'shell'

# window-4
tmux new-window -t 'code' -a -n 'notes'

# wrap-up
tmux select-window -t 'code':1
tmux -2 attach -t 'code'
