#!/bin/bash
SESSION=`basename $PWD`

tmux -2 new-session -d -s 'code'

# window-1
tmux rename-window -t 'code':1 'vim'
tmux split-window   -v -p 30

# window-2
tmux new-window -t 'code' -a -n 'git'
tmux split-window -v -p 30

# window-3
tmux new-window -t 'code' -a -n 'shell'

# wrap-up
tmux select-window -t 'code':1
tmux -2 attach -t 'code'

# old stuff
# tmux -2 new-session -d -s $SESSION
#
# tmux rename-window -t $SESSION:1 vim
# tmux split-window   -v -p 30
# # tmux select-pane -t 0
# # tmux resize-pane -R 30
#
# tmux new-window -t $SESSION -a -n git
# tmux split-window -v
# tmux select-pane -t 0
# tmux resize-pane -R 30
#
# tmux new-window -t $SESSION -a -n shell
# tmux split-window -h
# tmux select-pane -t 0
#
# # tmux new-window -t $SESSION -a -n logs
# # tmux split-window -v
# # tmux select-pane -t 0
# #
# # tmux new-window -t $SESSION -a -n elinks 'elinks -no-connect'
# # tmux split-window -h
# # tmux select-pane -t 0
# # tmux resize-pane -R 30
#
# tmux select-window -t $SESSION:1
# tmux -2 attach -t $SESSION
